export const ADD_TO_CATEGORY="ADDTOCATEGORY";
export const CATEGORY_ARRAY_SUCCESS="CATEGORYARRAYSUCCESS";
export const CATEGORY_ARRAY_START="CATEGORYARRAYSTART";
export const CATEGORY_ARRAY_FAIL="CATEGORYARRAYFAIL";

export const SUPPLIER_DEATILS_SUCCESS="SUPPLIERDETAILSSUCCESS"
export const SUPPLIER_DEATILS_START="SUPPLIERDETAILSSTART"
export const SUPPLIER_DEATILS_FAIL="SUPPLIERDETAILSFAIL"

export const SELLER_INFO_SUCCESS="SELLERINFOSUCCESS"
export const SELLER_INFO_START="SELLERINFOSTART"
export const SELLER_INFO_FAIL="SELLERINFOFAIL"

export const ADD_TO_CART="ADDTOCART";
export const UPDATE_CART="UPDATECART";
export const UPDATE_CART_INDEX="UPDATECARTINDEX";

export const SETEADDRESS_ERROR="SETADDRESSERROR"
export const ADD_ADDRESS="ADDADDRESS";
export const ADDRESS_FAIL="ADDRESSFAIL";
export const FETCH_ADDRESS="FETCHADDRESS";
export const SET_ADDRESS_STATUS="SETADDRESSSTATUS"
export const UPDATE_ADDRESS="UPDATEADDRESS"
export const UPDATE_ADDRESS_FAIL="UPSDATEADDRESSFAIL"
export const DELETE_ADDRESS="DELETEADDRESS";
export const DELETE_ADDRESS_FAIL="DELETEADDRESSFAIL"

export const PRODUCT_DATA_START="PRODUCTDATASTART";
export const PRODUCT_DATA_FAIL="PRODUCTDATAFAIL";
export const PRODUCT_DATA_SUCCESS="PRODUCTDATASUCCESS";
export const PRODUCT_DATA_BYCATEGORY="PRODUCTDATABYCATEGORY";
export const PRODUCT_DATA_BYCATEGORY_START="PRODUCTDATABYCATEGORYSTART";
export const PRODUCT_DATA_BYCATEGORY_FAIL="PRODUCTDATABYCATEGORYFAIL";
export const STORE_AUTH_DATA="AUTHDATA"
export const CHECKOUT_SUCCESS="CHECKOUTSUCCESS";
export const CHECKOUT_FAIL="CHECKOUTFAIL";
export const SET_CHECKOUT_STATUS="SETCHECKOUTSTATUS";

export const AUTH_SUCCESS="AUTHSUCCESS";
export const AUTH_FAIL="AUTHFAIL";
export const AUTH_STATUS="AUTHSTATUS";
export const VERIFY_OTP_SUCCESS="VERIFYOTPSUCCESS";
export const VERIFY_OTP_FAIL="VERIFYOTPFAIL";
export const RESEND_OTP_SUCCESS="RESENDSUCCESS";
export const RESEND_OTP_FAIL="RESENDFAIL";

export const FETCH_ORDERS="FECTHORDERS";
export const FETCH_ORDERS_FAIL="FECTHORDERSFAIL";
export const SET_ORDERS_STATUS="SETORDERSSTATUS"